name: bug report
description: the mod has a problem or it causes a crash.
labels: [bug]
assignees: [orifu]

body:
  - type: markdown
    attributes:
      value: |
        thank you for making a bug report! here's the information we need:
  - type: dropdown
    id: minecraft
    attributes:
      label: minecraft version
      description: which version of minecraft are you using?
      options:
        - 1.21.5 (Spring to Life)
        - 1.21.4 (The Garden Awakens)
        - 1.21.3 (Bundles of Bravery)
        - 1.21.1 (Tricky Trials)
        - 1.20.6 (Armored Paws)
        - 1.20.4 (Bats and Pots)
        - 1.20.2
        - 1.20.1
        - 1.19.4
        - 1.19.3
        - 1.19.2
        - 1.18.2
        - 1.17.1
        - 1.16.5
        - 1.15.2
        - another version
    validations:
      required: true
  - type: dropdown
    id: mod-version
    attributes:
      label: mod version
      description: which version of skin overrides are you using?
      options:
        - 2.3.0
        - 2.2.3
        - 2.2.2
        - 2.2.1
        - 2.2.0
        - 2.1.1
        - 2.1.0
        - 2.0.0
        - 1.0.0
        - beta
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: mod loader
      description: which mod loader are you using?
      options:
        - fabric
        - quilt
        - neoforge
        - i don't know/other
  - type: textarea
    id: description
    attributes:
      label: what went wrong?
      description: describe what went wrong (did it crash? is something not working?)
      placeholder: |
        the game crashes when trying to...
    validations:
      required: true
  - type: input
    id: log
    attributes:
      label: log file
      description: >
        having a log file is very helpful for debugging. if you can, upload your log
        using a website like [mclo.gs](https://mclo.gs/) and add the link here.
      placeholder: https://mclo.gs/...
